version: '3.8'

services:
  neo4j:
    image: neo4j:5.17
    container_name: neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/mysecret
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 2G
    ports:
      - "7474:7474"  # Neo4j Web Interface
      - "7687:7687"  # Bolt Protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/var/lib/neo4j/conf
    networks:
      - neo4j_network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:

networks:
  neo4j_network:
    driver: bridge